-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 20:48:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  `Capacidade` INT NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Cargo` VARCHAR(255) NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `idEquipamento` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `Sala_idSala` INT NOT NULL,
  `Data` DATETIME NOT NULL,
  `Funcionario` INT NOT NULL,
  `Pauta` LONGTEXT NULL,
  `Ata` LONGTEXT NULL,
  INDEX `fk_Reserva_Sala_idx` (`Sala_idSala` ASC) VISIBLE,
  PRIMARY KEY (`idReserva`),
  CONSTRAINT `fk_Reserva_Sala`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservaEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservaEquipamento` (
  `idEquipamento` INT NOT NULL,
  `idReserva` INT NOT NULL,
  PRIMARY KEY (`idEquipamento`, `idReserva`),
  INDEX `fk_Equipamento_has_Reserva_Reserva1_idx` (`idReserva` ASC) VISIBLE,
  INDEX `fk_Equipamento_has_Reserva_Equipamento1_idx` (`idEquipamento` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento_has_Reserva_Equipamento1`
    FOREIGN KEY (`idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipamento_has_Reserva_Reserva1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participante` (
  `idReserva` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `AceitouAta` TINYINT NULL,
  PRIMARY KEY (`idReserva`, `idFuncionario`),
  INDEX `fk_Reserva_has_Funcionario_Funcionario1_idx` (`idFuncionario` ASC) VISIBLE,
  INDEX `fk_Reserva_has_Funcionario_Reserva1_idx` (`idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_has_Funcionario_Reserva1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Funcionario_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
